### ISSUE TITLE
회원등급 할인 이벤트 구현

### ISSUE THREAD

**Issue by kwhyo** [choijungp/Project3#15]
할인 이벤트 : 구매 내역(가격)에 따른 구매자 랭킹 (1, 2, 3)
: basic = 0 ~ 50,000원, 할인율 0 %
: silver = 50,001원 ~ 100,000원, 할인율 3 %
: gold = 100,001원 ~ , 할인율 5 %

위키 내용에 따라 회원 등급 할인 이벤트 구현했습니다.
회원 승급은 회원이 새 주문을 할 때 발생합니다.

회원 승급에 대한 안내 메시지를 추가로 구현할 예정입니다.

**Comment by choijungp** [comment]
확인했습니다.

**Comment by kwhyo** [comment]
silver = 500,001원 ~ 1,000,000원, 할인율 3 %
gold = 1,000,001원 ~ , 할인율 5 %
로 기준을 수정했습니다. 이슈 닫겠습니다.
